# Generated by Django 4.1.3 on 2022-11-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promocionar_a',
            field=models.ManyToManyField(to='app.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='BVWVTZK', editable=False, max_length=7, null=True),
        ),
    ]
