# Generated by Django 4.1.3 on 2022-11-24 03:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_descuento_alter_client_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='2KH7CP6', editable=False, max_length=7, null=True),
        ),
    ]
