# Generated by Django 4.1.3 on 2022-11-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_codigo_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='IRXJ8BT', editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promocionar_a',
            field=models.ManyToManyField(blank=True, null=True, to='app.client'),
        ),
    ]
