# Generated by Django 4.1.3 on 2022-11-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_codigo_alter_product_promocionar_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='TDJS05S', editable=False, max_length=7, null=True),
        ),
    ]
