# Generated by Django 4.1.3 on 2022-11-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_citas_fecha_nacimiento_alter_client_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='fecha_nacimiento',
            new_name='fecha_cita',
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='3ZUJTZB', editable=False, max_length=7, null=True),
        ),
    ]
