# Generated by Django 4.1.3 on 2022-11-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_fecha_nacimiento_citas_fecha_cita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='esta_pagada',
            new_name='activa',
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='KNAJJWE', editable=False, max_length=7, null=True),
        ),
    ]
