# Generated by Django 4.1.3 on 2023-06-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_client_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='detalles_de_facturacion',
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='R5ZYPAE', editable=False, max_length=7, null=True),
        ),
    ]
