# Generated by Django 4.1.3 on 2023-06-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_client_detalles_de_facturacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='especie',
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='MWVNRUA', editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
