# Generated by Django 4.1.3 on 2023-06-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_paciente_especie_alter_client_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.TextField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='FO2NXWO', editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(),
        ),
    ]
