# Generated by Django 4.1.3 on 2023-06-30 03:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_paciente_sexo_alter_client_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='EEN0WYL', editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[app.models.non_negative_validator]),
        ),
    ]
