# Generated by Django 4.1.3 on 2023-07-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_client_apellido_alter_client_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='EKYSUMT', editable=False, max_length=7, null=True),
        ),
    ]
