# Generated by Django 4.1.3 on 2023-07-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_client_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='1SOYDDA', editable=False, max_length=7, null=True),
        ),
    ]
