# Generated by Django 4.1.3 on 2023-07-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_client_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='XZRUWHZ', editable=False, max_length=7, null=True),
        ),
    ]
