# Generated by Django 4.1.3 on 2023-07-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_citas_hora_alter_client_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pasada', 'Pasada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='JA6D66V', editable=False, max_length=7, null=True),
        ),
    ]
