# Generated by Django 4.1.3 on 2023-07-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_citas_estado_alter_client_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='estado',
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='WMICFF8', editable=False, max_length=7, null=True),
        ),
    ]
