# Generated by Django 4.1.3 on 2023-07-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_citas_estado_alter_client_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='diagnostico_preliminar',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='examen_fisico',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='patologia',
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='NW0WXZN', editable=False, max_length=7, null=True),
        ),
    ]
