# Generated by Django 4.1.3 on 2023-07-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_citas_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='codigo',
            field=models.CharField(default='T88RB30', editable=False, max_length=7, null=True),
        ),
    ]
