"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^$enqil(gqp4&i=+@0zw17s$&)+at1p+t=#8uo$mo(latzsz(8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEPLOYADO = False
ALLOWED_HOSTS = ['*']
# if DEPLOYADO:
#     YOUR_DOMAIN = 'https://canipet.pythonanywhere.com'
#     ALLOWED_HOSTS = ['canipet.pythonanywhere.com']
# else:
#     YOUR_DOMAIN = 'http://127.0.0.1:8000'
#     ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
        "corsheaders",
     'api',
       'rest_framework',
    'mobile',
    'crispy_forms',
    'app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
         "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
    
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MEDIA_URL = '/media/'  # or any prefix you choose

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dolbvx3l6',
    'API_KEY': '546194191714711',
    'API_SECRET': '-gBY-QkYTjHPHO17kz11cD-b7Uw'
}

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "canipet.ni@gmail.com"
EMAIL_HOST_PASSWORD = "csoaqagdvkqkvgsv"
EMAIL_USE_SSL = True

STRIPE_SECRET_KEY = 'sk_test_51Li94GICcpUoya7HS8byhyEqbPBw0ORbaus7WcJnHzbik4nckly31vyxmsEFafuhJktS0StteF9RuhNkIBYXezLT00ffAgU7Sb'
STRIPE_PUBLIC_KEY = 'pk_test_51Li94GICcpUoya7HEPpVsTIiaGZOepYQR2BZ0lWlnuBFJP1mEPWgnK7fxhRC39HoH93E1Zs6sq6NCUgiQQhFGx6Y0018fDtvCk'
STRIPE_WEBHOOK_SECRET = 'whsec_3f638ecf53d7fcefc8759e3ef072d5d10c4cb20056ebb70b58beab9b1bbe89da'

if DEPLOYADO:
    import cloudinary
    cloudinary.config(
    cloud_name = 'dolbvx3l6',
    api_key = '546194191714711',
    api_secret = '-gBY-QkYTjHPHO17kz11cD-b7Uw',
    api_proxy = "http://proxy.server:3128"
    )
    import cloudinary.uploader
    import cloudinary.api


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '1011049325293-ifrv7ir2jk8j7l92stnbh5risuh99cdp.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'AUTH_PARAMS': {
            'prompt': 'select_account'
        }
    }
}

LOGIN_REDIRECT_URL = '/app/'

CORS_ALLOW_ALL_ORIGINS = True